version: "3.6"

volumes:
  volapplication:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ft_traceroute/

  voltest:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./test/

services:
  application:
    container_name: traceroute
    build: ./docker/traceroute/
    volumes:
    - volapplication:/ft_traceroute/
    restart: always

  test:
    container_name: test
    build: ./docker/test/
    volumes:
    - voltest:/test/
    sysctls:
      - net.ipv4.icmp_echo_ignore_all=1
    restart: always